const TOAST = {
  EMAIL_EXISTED: "Email is exist!",
  NAME_EXISTED: "Name is exist!",
  EMAIL_IS_NOT_EXISTED: "Email is not exist!",
  REGISTER_SUCCESSFULLY: "Register Successfully!",
  REGISTER_WITH_GOOGLE_SUCCESSFULLY: "Register with google successfully!",
  REQUEST_FORGOT_PASSWORD_SUCCESSFULLY: "Request forgot password successfully!",
  SEND_EMAIL_SUCCESSFULLY: "Send email successfully",
  SEND_EMAIL_FAILED: "Send email fail",
  USER_NOT_FOUND: "User not found!",
  IN_CORRECT_VERIFY_CODE: "In correct verify code!",
  VERIFY_CODE_EXPIRED: "Verify code expired!",
  VERIFY_SUCCESSFULLY: "Verify successfully!",
  USER_ACTIVATED: "User activated",
  USER_NOT_ACTIVATED: "User not activated",
  USER_BANNED: "User banned",
  LOGIN_SUCCESSFULLY: "Login Successfully!",
  IN_CORRECT_PASSWORD: "In correct password!",
  UPDATE_USER_SUCCESSFULLY: "Update user successfully",
  CREATE_BRAND_SUCCESSFULLY: "Create new brand successfully",
  BRAND_NOT_FOUND: "Brand not found!",
  UPDATE_BRAND_SUCCESSFULLY: "Update brand successfully",
  CATEGORY_NOT_FOUND: "Category not found!",
  UPDATE_CATEGORY_SUCCESSFULLY: "Update category successfully",
  CREATE_PRODUCT_SUCCESSFULLY: "Create new product successfully",
  UPDATE_PRODUCT_SUCCESSFULLY: "Update product successfully",
  SKU_EXISTED: "Sku is exist!",
  PRODUCT_NOT_FOUND: "Product not found!",
  // cart
  CREATE_CARTS_SUCCESSFULLY: "Create new cart successfully",
  GET_CARTS_SUCCESSFULLY: "Get carts successfully",
  GET_CART_SUCCESSFULLY: "Get cart successfully",
  CART_NOT_FOUND: "Cart not found!",
  UPDATE_CARTS_SUCCESSFULLY: "Update product successfully",
  // order
  CREATE_ORDER_SUCCESSFULLY: "Create new order successfully",
  GET_ORDER_FAILED: "Get order failed",
  ORDER_NOT_FOUND: "Order not found!",
  GET_ORDER_SUCCESSFULLY: "Get order successfully",
  GET_ORDERS_SUCCESSFULLY: "Get orders successfully",
  CREATE_ORDER_FAILED: "Create new order failed",
  PAYMENT_VN_PAY_SUCCESSFULLY: "Payment vn pay successfully",
  // transaction
  ORDER_HAD_TRANSACTION: "Order paid",
  CREATE_TRANSACTION_SUCCESSFULLY: "Create new transaction successfully",
  LINK_IS_NOT_VALID: "Link  inValid!",
  GET_TRANSACTION_SUCCESSFULLY: "Get transaction successfully",
  //
  ACCOUNT_TYPE_INVALID: "Account type invalid or password is not null!",
  WRONG_PASSWORD: "Wrong password!",
  UPDATE_PASSWORD_SUCCESSFULLY: "Update password successfully!",
  PASSWORD_NULL: "Your account don't have password. Please login with google and update you password!",
  //
  UPDATE_REQ_FORGOT_PASSWORD_TOKEN_SUCCESSFULLY:
    "Update req forgot password token successfully!",
  TOKEN_INVALID: "Token inValid or expired!",
  UPDATE_PASSWORD_SUCCESSFULLY: "Update password successfully",
  // review
  CREATE_REVIEW_SUCCESSFULLY: "Create new review successfully",
  REVIEWED_THIS_PRODUCT: "You review this product!",
  PRODUCT_HAS_NOT_BOUGHT: "Product has not bought!",
   GET_REVIEW_SUCCESSFULLY: "Get review successfully",
};

module.exports = TOAST;
